### ISSUE TITLE
[feature request] add placeNL discord / reddit buttons and button for artist page

### ISSUE THREAD

**Issue by Sloth-on-meth** [PlaceNL/Chief#13]
testing

**Comment by NoahvdAa** [comment]
> button for artist page
<img width="558" alt="image" src="https://github.com/PlaceNL/Chief/assets/44026893/9fd6412f-85c7-462d-b7bc-e07f4474b692">

as for the rest, chief is intended to be semi-neutral branded, so not sure if we should link that.

**Comment by Sloth-on-meth** [comment]
@NoahvdAa if we're keeping it semi-neutral, users from other subreddits can fork it and use their own discord / reddit, right?
