### ISSUE TITLE
'Invalid Discord authentication code! It may have expired' when not pushing for a while

### ISSUE THREAD

**Issue by Visne** [PlaceNL/Chief#18]
If not pushing a new template for a while and then pushing one, I get the error from the title. If I then make the same order right away Discord authentication works fine. This has happened consistently for a while.

**Comment by NoahvdAa** [comment]
Does authentication happen before or after you push the template? If it's before, we've moved it to after you've filled everything out to solve this exact problem, make sure you're on the latest version.

**Comment by Visne** [comment]
Yep, after. Chief is up to date.

**Comment by NoahvdAa** [comment]
That's odd, so you click log in and push, discord oauth opens and you sign in and it still says your session expired?

**Comment by Visne** [comment]
I think I might not have restarted Chief, I'm on latest now and it seems to be working fine. Apologies for the confusion.
